export const uids = {
	HOMEPAGE: 'W93_RBEAACsAXn5F',
	ABOUT_US: 'WoBS0iYAAOw7o08v',
  //FAQ: 'WoBNBCYAANo4ozWk',
	TERMS: 'WoRP8igAACIAcojC',
	PRIVACY: 'WoRQ-SgAACgAco1K',
	CONTACT_US: 'WoRRbigAACgAco9L',
	REGISTRATION: 'Wu7sWiUAAKoBSMxT',
	LANGUAGE_PRACTICE: 'W-qgQhAAACsAblRR',
	LANGUAGE_LEARNERS: 'W_vZPBEAADEAEjuB',
	IMMIGRATION_ADVICE: 'W-p01BAAACkAbZQ-',
	SHORT_REVIEWS: 'W-0TkBAAACkAeSLm',
	FAQ: 'W_V1PhEAACsAzO48',
};
