export const uids = {
	'en-us': {
		HOMEPAGE: 'W93_RBEAACsAXn5F',
		ABOUT_US: 'WoBS0iYAAOw7o08v',
		//FAQ: 'WoBNBCYAANo4ozWk',
		TERMS: 'WoRP8igAACIAcojC',
		PRIVACY: 'WoRQ-SgAACgAco1K',
		CONTACT_US: 'WoRRbigAACgAco9L',
		REGISTRATION: 'Wu7sWiUAAKoBSMxT',
		LANGUAGE_PRACTICE: 'W-qgQhAAACsAblRR',
		LANGUAGE_LEARNERS: 'W-0bnhAAACkAeUZX',
		IMMIGRATION_ADVICE: 'W-p01BAAACkAbZQ-',
		SHORT_REVIEWS: 'W-0TkBAAACkAeSLm',
		FAQ: 'W_V1PhEAACsAzO48',
	},
	ru: {
		HOMEPAGE: 'W_0QkREAAC8AF6jE',
		/*ABOUT_US: 'WoBS0iYAAOw7o08v',*/
		TERMS: 'W_1UXxEAADEAGNAJ',
		PRIVACY: 'W_1TdBEAADEAGMv2',
		/*CONTACT_US: 'WoRRbigAACgAco9L',
		REGISTRATION: 'Wu7sWiUAAKoBSMxT',
		LANGUAGE_PRACTICE: 'W-qgQhAAACsAblRR',*/
		LANGUAGE_LEARNERS: 'W_vZPBEAADEAEjuB',
		/*IMMIGRATION_ADVICE: 'W-p01BAAACkAbZQ-',
		SHORT_REVIEWS: 'W-0TkBAAACkAeSLm',
		FAQ: 'W_V1PhEAACsAzO48',*/
	}
	
};
